// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAADgfDmVGEwO4QooOUGqOLlQQW4eNjSE4',
    appId: '1:637420739963:web:db90c3b15252782af731de',
    messagingSenderId: '637420739963',
    projectId: 'holbegram-66188',
    authDomain: 'holbegram-66188.firebaseapp.com',
    storageBucket: 'holbegram-66188.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS050yN__mr2BkY4eoSUGbAGY1zHaS3gg',
    appId: '1:637420739963:android:23b018183684d513f731de',
    messagingSenderId: '637420739963',
    projectId: 'holbegram-66188',
    storageBucket: 'holbegram-66188.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM0mjBBopBr0zUc8ASY_mmuestE4-KFKg',
    appId: '1:637420739963:ios:e9d6969d3eedee84f731de',
    messagingSenderId: '637420739963',
    projectId: 'holbegram-66188',
    storageBucket: 'holbegram-66188.appspot.com',
    iosBundleId: 'com.example.holbegram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM0mjBBopBr0zUc8ASY_mmuestE4-KFKg',
    appId: '1:637420739963:ios:a4161fa759d201e6f731de',
    messagingSenderId: '637420739963',
    projectId: 'holbegram-66188',
    storageBucket: 'holbegram-66188.appspot.com',
    iosBundleId: 'com.example.holbegram.RunnerTests',
  );
}
